project:
  type: website

website:
  navbar:
    title: false
    background: light
    foreground: success
    search: false
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/josepenabravo
      - icon: github
        href: https://github.com/jpenabravo
      - icon: share
    left:
      - text: "About"
        href: index.qmd
      - text: "More"
        menu: 
          - projects.qmd
          - CV.qmd
          - links.qmd
  back-to-top-navigation: true

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

