project:
  type: website

website:
  navbar:
    title: false
    background: light
    foreground: success
    search: false
    tools:
      - icon: linkedin
      - icon: github
      - icon: share
    left:
      - text: "About"
        href: index.qmd
      - text: "More"
        menu: 
          - projects.qmd
          - CV.qmd
          - links.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

